name: untitled4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.10

  # Firebase
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.11

  # Локални нотификации
  flutter_local_notifications: ^13.0.0

  # HTTP и други помошни пакети
  http: ^1.5.0
  timezone: ^0.9.0   # <= верзија што работи со Flutter 3.35.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
